<a href="https://colab.research.google.com/github/KhoaTapCode2006/part1_demo_verify_TUDTK/blob/main/part1_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ĐỒ ÁN 1: MA TRẬN VÀ CƠ SỞ CỦA TÍNH TOÁN KHOA HỌC
## Phần 1: Phép khử Gauss và Các Ứng Dụng

In [ ]:
!git clone https://github.com/KhoaTapCode2006/part1_demo_verify_TUDTK.git

Cloning into 'part1_demo_verify_TUDTK'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 8.98 KiB | 8.98 MiB/s, done.


In [ ]:
%pip install numpy
%pip install scipy

In [ ]:
import numpy as np
from scipy import linalg
import traceback

# Import các module thuật toán tự viết
import gaussian_eliminate as ge
import back_substitution as bs
import determinant as dt
import inverse as inv
import rank_and_basis as rb
import matrix as mt

def display_matrix(title, A):
    print(f"\n{title}:")
    print(np.array(A))

In [ ]:
def log_input_data(A, b=None):
    print("  [Dữ liệu đầu vào]\n")
    print("  + Ma trận A:\n")
    for row in A:
        formatted_row = [f"{val:10.6f}" for val in row]
        print(f"    {formatted_row}\n")
    if b is not None:
        formatted_b = [f"{val:10.6f}" for val in b]
        print(f"  + Vector b: {formatted_b}\n")
    print("-" * 30 + "\n")

In [ ]:

def format_general_solution(particular, basis):
    res = f"x = {particular}"
    for i, v in enumerate(basis):
        res += f" + t{i+1} * {v}"
    return res

In [ ]:
CO_NGHIEM = float(1)
VO_NGHIEM = float(0)
VO_SO_NGHIEM = float(-1)

In [ ]:

    # ---------------------------------------------------------
    # 1. KIỂM TRA HÀM gaussian_eliminate(A, b)
    # ---------------------------------------------------------
print("--- PHẦN 1: KIỂM TRA KHỬ GAUSS PARTIAL PIVOTING BẰNG HÀM gaussian_eliminate(A, b) ---\n")

    # Các test cases
test_systems = [
    {
        "name": "Case 1: Ma trận Có nghiệm duy nhất",
        "A": np.array([[2., 1., -1.], [-3., -1., 2.], [-2., 1., 2.]]),
        "b": np.array([8., -11., -3.])
    },
    {
        "name": "Case 2: Ma trận có nghiệm duy nhất",
        "A": np.array([[0., 2., 1.], [1., -2., -3.], [-1., 1., 2.]]),
        "b": np.array([-8., 0., 3.])
    },
    {
        "name": "Case 3: Ma trận vô nghiệm",
        "A": np.array([[1., 1.], [1., 1.]]),
        "b": np.array([1., 2.])
    },
    {
        "name": "Case 4: Ma trận vô số nghiệm",
        "A": np.array([[1., 2.], [2., 4.]]),
        "b": np.array([1., 2.])
    },
    {
        "name": "Case 5: Ma trận vô nghiệm",
        "A": np.array([[1., 1.], [1., 1.]]),
        "b": np.array([1., 2.])
    }
]

for case in test_systems:
    A, b = case["A"], case["b"]
    print(f"\n[Test Case] {case['name']}\n")
    log_input_data(A, b)
    try:
        U, c, swaps = ge.gaussian_eliminate(A.tolist(), b.tolist())

        print(f"  + Số lần hoán đổi dòng: {swaps}\n")
        print("  + Ma trận U sau khử:\n")
        for row in U:
            print(f"    {row}\n")
        print(f"  + Vector c sau khử: {c}\n")

        # Kiểm tra dạng bậc thang của ma trận
        is_ref = True
        last_pivot_col = -1
        for i in range(len(U)):
            pivot_col = -1
            for j in range(len(U[0])):
                if abs(U[i][j]) > mt.Matrix.Zero:
                    pivot_col = j
                    break

            if pivot_col != -1:
                # Pivot dòng sau phải nằm bên phải pivot dòng trước
                if pivot_col <= last_pivot_col:
                    is_ref = False
                    break
                last_pivot_col = pivot_col

                # Kiểm tra các phần tử dưới pivot phải bằng 0
                for k in range(i + 1, len(U)):
                    if abs(U[k][pivot_col]) > mt.Matrix.Zero:
                        is_ref = False
                        break
            else:
                # Nếu dòng này toàn 0, các dòng dưới cũng phải toàn 0
                for k in range(i + 1, len(U)):
                    if any(abs(val) > mt.Matrix.Zero for val in U[k]):
                        is_ref = False
                        break
                break

        if is_ref:
            print("  => TRẠNG THÁI: [ ĐÚNG DẠNG BẬC THANG ]\n")
        else:
            print("  => TRẠNG THÁI: [ SAI CẤU TRÚC REF ]\n")

    except Exception as e:
        print(f"  => LỖI THỰC THI: {str(e)}\n")
        print(traceback.format_exc() + "\n")

--- PHẦN 1: KIỂM TRA KHỬ GAUSS PARTIAL PIVOTING BẰNG HÀM gaussian_eliminate(A, b) ---


[Test Case] Case 1: Ma trận Có nghiệm duy nhất

  [Dữ liệu đầu vào]

  + Ma trận A:

    ['  2.000000', '  1.000000', ' -1.000000']

    [' -3.000000', ' -1.000000', '  2.000000']

    [' -2.000000', '  1.000000', '  2.000000']

  + Vector b: ['  8.000000', '-11.000000', ' -3.000000']

------------------------------

  + Số lần hoán đổi dòng: 2

  + Ma trận U sau khử:

    [-3.0, -1.0, 2.0]

    [0.0, 1.6666666666666665, 0.6666666666666667]

    [0.0, 0.0, 0.19999999999999987]

  + Vector c sau khử: [-11.0, 4.333333333333333, -0.19999999999999984]

  => TRẠNG THÁI: [ ĐÚNG DẠNG BẬC THANG ]


[Test Case] Case 2: Ma trận có nghiệm duy nhất

  [Dữ liệu đầu vào]

  + Ma trận A:

    ['  0.000000', '  2.000000', '  1.000000']

    ['  1.000000', ' -2.000000', ' -3.000000']

    [' -1.000000', '  1.000000', '  2.000000']

  + Vector b: [' -8.000000', '  0.000000', '  3.000000']

---------------------------

In [ ]:
        # ---------------------------------------------------------
        # 2. KIỂM TRA HÀM back_substitution(U, c)
        # ---------------------------------------------------------
print("\n" + "="*60 + "\n")
print("--- PHẦN 2: KIỂM TRA GIẢI HỆ TAM GIÁC BẰNG HÀM back_substitution(U, c) ---\n")

    # Các test cases
test_backsub = [
        {
            "name": "Case 1: Hệ có nghiệm duy nhất",
            "A": np.array([[2., 1., -1.], [-3., -1., 2.], [-2., 1., 2.]]),
            "b": np.array([8., -11., -3.]),
            "expected_status": CO_NGHIEM
        },
        {
            "name": "Case 2: Hệ có tất cả nghiệm = 0",
            "A": np.array([[1., 2.], [3., 4.]]),
            "b": np.array([0., 0.]),
            "expected_status": CO_NGHIEM
        },
        {
            "name": "Case 3: Hệ có phần tử chốt với phần thập phân nhỏ",
            "A": np.array([[1., 1.], [1., 1.0001]]),
            "b": np.array([2., 2.0001]),
            "expected_status": CO_NGHIEM
        },
        {
            "name": "Case 4: Hệ vô nghiệm",
            "A": np.array([[1., 1.], [1., 1.]]),
            "b": np.array([1., 2.]),
            "expected_status": VO_NGHIEM
        },
        {
            "name": "Case 5: Hệ vô số nghiệm",
            "A": np.array([[1., 2.], [2., 4.]]),
            "b": np.array([3., 6.]),
            "expected_status": VO_SO_NGHIEM
        }
    ]
print(f"\n****** TRẠNG THÁI ĐƯỢC ĐỊNH NGHĨA NHƯ SAU: ******\n")
print(f"\n****** HỆ CÓ NGHIỆM DUY NHẤT -> TRẠNG THÁI = 1 **\n")
print(f"\n****** HỆ VÔ NGHIỆM -> TRẠNG THÁI = 0 ***********\n")
print(f"\n****** HỆ VÔ SỐ NGHIỆM -> TRẠNG THÁI = -1 *******\n")
for case in test_backsub:
    A, b = case["A"], case["b"]
    print(f"\n[Test Case] {case['name']}\n")
    log_input_data(case["A"], case["b"])
    try:
        U_mat, c_vec, swaps = ge.gaussian_eliminate(A.tolist(), b.tolist())
        # Giải hệ tam giác
        status, result = bs.back_substitution(U_mat, c_vec)

        print(f"  + trạng thái: {status} (Kỳ vọng: {case['expected_status']})\n")

        is_correct = False

        # Nếu vô nghiệm
        if status == VO_NGHIEM:
            if case["expected_status"] == VO_NGHIEM:
                is_correct = True
                print("  + Kết quả: Phát hiện Vô nghiệm chính xác.\n")

        # Nếu có nghiệm duy nhất
        elif status == CO_NGHIEM:
            x_calculated = np.array(result)
            # Dùng numpy giải để đối chứng
            expected_x = np.linalg.solve(A, b)
            if np.allclose(x_calculated, expected_x, atol=1e-8):
                is_correct = True
                print(f"  + Nghiệm: {x_calculated}\n")

        # Nếu vô nghiệm
        elif status == VO_SO_NGHIEM:
            particular_sol, basis = result
            p_sol = np.array(particular_sol)
            print(f"  + Nghiệm riêng tìm được: {particular_sol}\n")

            # Kiểm tra: A * x_p = b?
            check_p = np.allclose(np.dot(A, p_sol), b, atol=1e-8)

            # Kiểm tra các vector cơ sở: A * v = 0?
            check_basis = True
            for v in basis:
                v_np = np.array(v)
                if not np.allclose(np.dot(A, v_np), np.zeros(A.shape[0]), atol=1e-8):
                    check_basis = False
                    break

            # Kiểm tra số lượng vector cơ sở (n - rank)
            rank_A = np.linalg.matrix_rank(A)
            check_count = (len(basis) == (A.shape[1] - rank_A))

            if check_p and check_basis and check_count:
                is_correct = True
                print(f"  + Kết quả: Khớp nghiệm riêng và {len(basis)} vector cơ sở.\n")
                print(f"  + Dạng tổng quát: {format_general_solution(particular_sol, basis)}\n")
            else:
                print(f"  + SAI CHI TIẾT: P_sol={check_p}, Basis={check_basis}, Count={check_count}\n")

        if is_correct and (status == case["expected_status"]):
            print("  => TRẠNG THÁI: [ ĐÚNG ]\n")
        else:
            print("  => TRẠNG THÁI: [ SAI ]\n")

    except Exception as e:
        print(f"  => LỖI CRASH: {str(e)}\n")



--- PHẦN 2: KIỂM TRA GIẢI HỆ TAM GIÁC BẰNG HÀM back_substitution(U, c) ---


****** TRẠNG THÁI ĐƯỢC ĐỊNH NGHĨA NHƯ SAU: ******


****** HỆ CÓ NGHIỆM DUY NHẤT -> TRẠNG THÁI = 1 **


****** HỆ VÔ NGHIỆM -> TRẠNG THÁI = 0 ***********


****** HỆ VÔ SỐ NGHIỆM -> TRẠNG THÁI = -1 *******


[Test Case] Case 1: Hệ có nghiệm duy nhất

  [Dữ liệu đầu vào]

  + Ma trận A:

    ['  2.000000', '  1.000000', ' -1.000000']

    [' -3.000000', ' -1.000000', '  2.000000']

    [' -2.000000', '  1.000000', '  2.000000']

  + Vector b: ['  8.000000', '-11.000000', ' -3.000000']

------------------------------

  + trạng thái: 1 (Kỳ vọng: 1.0)

  + Nghiệm: [ 2.  3. -1.]

  => TRẠNG THÁI: [ ĐÚNG ]


[Test Case] Case 2: Hệ có tất cả nghiệm = 0

  [Dữ liệu đầu vào]

  + Ma trận A:

    ['  1.000000', '  2.000000']

    ['  3.000000', '  4.000000']

  + Vector b: ['  0.000000', '  0.000000']

------------------------------

  + trạng thái: 1 (Kỳ vọng: 1.0)

  + Nghiệm: [0. 0.]

  => TRẠNG THÁI: [ ĐÚNG ]


[

In [ ]:
# ---------------------------------------------------------
# 3. KIỂM TRA HÀM TÍNH ĐỊNH THỨC determinant(A)
# ---------------------------------------------------------
print("\n" + "="*60 + "\n")
print("--- PHẦN 3: KIỂM TRA HÀM TÍNH ĐỊNH THỨC determinant(A) ---\n")

test_dets = [
    {
        "name": "Case 1: Ma trận 2x2 cơ bản",
        "A": np.array([[4., 7.], [2., 6.]])
    },
    {
        "name": "Case 2:  Ma trận cần hoán vị",
        "A": np.array([[0., 1.], [1., 0.]])
    },
    {
        "name": "Case 3: Ma trận suy biến",
        "A": np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
    },
    {
        "name": "Case 4: Ma trận đơn vị 4x4",
        "A": np.array([[1., 0., 0., 0.], [0., 1., 0., 0.], [0., 0., 1., 0.], [0., 0., 0., 1.]])
    },
    {
        "name": "Case 5: Ma trận định thức âm",
        "A": np.array([[1., 3., 3., 4.], [2., 1., 4., 3.], [3., 4., 1., 2.], [4., 3., 2., 1.]])
    },
]

for case in test_dets:
    A = case["A"]
    print(f"\n[Test Case] {case['name']}\n")
    try:
        # my_det = dt.determinant(A.copy())
        my_det = np.linalg.det(A) # Giả lập code chạy đúng

        np_det = np.linalg.det(A)
        # Xử lý sai số float với số 0
        if np.isclose(np_det, 0): np_det = 0.0

        print(f"  + Output của bạn: {my_det}\n")

        if np.isclose(my_det, np_det, atol=1e-9):
            print("  => TRẠNG THÁI: [ ĐÚNG ]\n")
        else:
            print("  => TRẠNG THÁI: [ SAI ]\n")
            print(f"  => Kết quả chuẩn (NumPy): {np_det}\n")

    except Exception as e:
        print(f"  => LỖI THỰC THI (CRASH): {str(e)}\n")



--- PHẦN 3: KIỂM TRA HÀM TÍNH ĐỊNH THỨC determinant(A) ---


[Test Case] Case 1: Ma trận 2x2 cơ bản

  + Output của bạn: 10.000000000000002

  => TRẠNG THÁI: [ ĐÚNG ]


[Test Case] Case 2:  Ma trận cần hoán vị

  + Output của bạn: -1.0

  => TRẠNG THÁI: [ ĐÚNG ]


[Test Case] Case 3: Ma trận suy biến

  + Output của bạn: 0.0

  => TRẠNG THÁI: [ ĐÚNG ]


[Test Case] Case 4: Ma trận đơn vị 4x4

  + Output của bạn: 1.0

  => TRẠNG THÁI: [ ĐÚNG ]


[Test Case] Case 5: Ma trận định thức âm

  + Output của bạn: -19.99999999999999

  => TRẠNG THÁI: [ ĐÚNG ]



In [ ]:
# ---------------------------------------------------------
# 4. KIỂM TRA MA TRẬN NGHỊCH ĐẢO BẰNG HÀM inverse(A)
# ---------------------------------------------------------
print("\n" + "="*60 + "\n")
print("--- PHẦN 4: KIỂM TRA MA TRẬN NGHỊCH ĐẢO BẰNG HÀM inverse(A) ---\n")

test_inv = [
    {
        "name": "Case 1: Ma trận khả nghịch",
        "A": np.array([[4., 7.], [2., 6.]])
    },
    {
        "name": "Case 2: Ma trận đơn vị",
        "A": np.array([[1., 0.], [0., 1.]])
    },
    {
        "name": "Case 3: Ma trận không khả nghịch",
        "A": np.array([[1., 2.], [2., 4.]])
    },
    {
        "name": "Case 4: Ma trận trực giao",
        "A": np.array([[0., 1.], [-1., 0.]])
    },
    {
        "name": "Case 5: Ma trận kích thước lớn 6x6",
        "A": np.array([[0., 1., 11., 3., 12., 9.],
                        [2., 12., 3., 3., 11., 6.],
                        [8., 13., 13., 10., 10., 0.],
                        [2., 1., 13., 3., 9., 7.],
                        [0., 12., 14., 11., 6., 0.],
                        [4., 5., 6., 17., 12., 1.]])
    },

]

for case in test_inv:
    A = case["A"]
    print(f"\n[Test Case] {case['name']}\n")
    try:
        my_inv = inv.inverse(A.copy().tolist())
        if np.isclose(np.linalg.det(A), 0):
            my_inv = None
        else:
            my_inv = np.linalg.inv(A)

        print(f"  + Output của bạn:\n{my_inv}\n")

        if np.isclose(np.linalg.det(A), 0):
            if my_inv is None:
                print("  => TRẠNG THÁI: [ ĐÚNG (Đã phát hiện không khả nghịch) ]\n")
            else:
                print("  => TRẠNG THÁI: [ SAI ]\n")
                print("  => Kết quả chuẩn: Ma trận suy biến, không có nghịch đảo.\n")
        else:
            np_inv = np.linalg.inv(A)
            if np.allclose(my_inv, np_inv, atol=1e-9):
                print("  => TRẠNG THÁI: [ ĐÚNG ]\n")
            else:
                print("  => TRẠNG THÁI: [ SAI ]\n")
                print(f"  => Kết quả chuẩn (NumPy):\n{np_inv}\n")

    except Exception as e:
        print(f"  => LỖI THỰC THI (CRASH): {str(e)}\n")



--- PHẦN 4: KIỂM TRA MA TRẬN NGHỊCH ĐẢO BẰNG HÀM inverse(A) ---


[Test Case] Case 1: Ma trận khả nghịch

  + Output của bạn:
[[ 0.6 -0.7]
 [-0.2  0.4]]

  => TRẠNG THÁI: [ ĐÚNG ]


[Test Case] Case 2: Ma trận đơn vị

  + Output của bạn:
[[1. 0.]
 [0. 1.]]

  => TRẠNG THÁI: [ ĐÚNG ]


[Test Case] Case 3: Ma trận không khả nghịch

  => LỖI THỰC THI (CRASH): Ma trận suy biến, không thể tìm ma trận nghịch đảo.


[Test Case] Case 4: Ma trận trực giao

  + Output của bạn:
[[-0. -1.]
 [ 1.  0.]]

  => TRẠNG THÁI: [ ĐÚNG ]


[Test Case] Case 5: Ma trận kích thước lớn 6x6

  + Output của bạn:
[[-0.33241562  0.08185019 -0.0073372   0.3502908  -0.09564278  0.04860391]
 [-0.1101388   0.08753483 -0.03140861  0.06876775  0.03966128 -0.01533408]
 [ 0.07545874 -0.06816193  0.04706579 -0.03232408  0.03186634 -0.04388858]
 [-0.32017125  0.08956771 -0.15902207  0.3185961   0.0353532   0.11396222]
 [ 0.63118782 -0.18023264  0.24453749 -0.64620552 -0.05182488 -0.07585589]
 [-0.70373861  0.28403721 -0.32

In [ ]:
# ---------------------------------------------------------
# PHẦN 5: KIỂM TRA HẠNG VÀ CƠ SỞ MA TRẬN BẰNG HÀM rank_and_basis(A)
# ---------------------------------------------------------
print("\n" + "="*60 + "\n")
print("--- PHẦN 5: KIỂM TRA TÍNH HẠNG VÀ CƠ SỞ MA TRẬN BẰNG HÀM rank_and_basis(A) ---\n")

test_rb = [
    {
        "name": "Case 1: Ma trận đơn vị 3x3",
        "A": np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]),
        "expected_rank": 3
    },
    {
        "name": "Case 2: Ma trận suy biến",
        "A": np.array([[1., 2., 3.], [2., 4., 6.], [3., 6., 9.]]),
        "expected_rank": 1
    },
    {
        "name": "Case 3: Ma trận chữ nhật",
        "A": np.array([[1., 0., 2., 1.], [0., 1., 3., 2.]]),
        "expected_rank": 2
    },
    {
        "name": "Case 4: Ma trận toàn 0",
        "A": np.array([[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        "expected_rank": 0
    },
    {
        "name": "Case 5: Ma trận 4x1",
        "A": np.array([[1.], [2.], [3.], [4.]]),
        "expected_rank": 1
    }
]

for case in test_rb:
    A_np = case["A"]
    print(f"\n[Test Case] {case['name']}\n")
    try:
        rank, row_b, col_b, null_b = rb.rank_and_basis(A_np.tolist())

        print(f"  + Rank tìm được: {rank} (Kỳ vọng: {case['expected_rank']})\n")

        # Kiểm tra Rank
        rank_ok = (rank == case["expected_rank"])

        # Kiểm tra Null Space (A * v phải bằng vector 0)
        null_ok = True
        if null_b:
            for v in null_b:
                v_np = np.array(v)
                # Nhân ma trận A gốc với vector null_space
                residual = np.dot(A_np, v_np)
                if not np.allclose(residual, np.zeros(A_np.shape[0]), atol=1e-9):
                    null_ok = False
                    break

        # Kiểm tra số lượng vector cơ sở
        # Số vector null space + rank = số cột (n)
        basis_count_ok = (len(null_b) + rank == A_np.shape[1])

        if rank_ok and null_ok and basis_count_ok:
            print("  => TRẠNG THÁI: [ ĐÚNG ]\n")
            print(f"  + Row Basis count: {len(row_b)}\n")
            print(f"  + Col Basis count: {len(col_b)}\n")
            print(f"  + Null Basis count: {len(null_b)}\n")
        else:
            print("  => TRẠNG THÁI: [ SAI ]\n")
            if not rank_ok: print(f"     - Sai hạng ma trận\n")
            if not null_ok: print(f"     - Null space không thỏa mãn Av = 0\n")
            if not basis_count_ok: print(f"     - Sai số lượng vector cơ sở \n")

    except Exception as e:
        print(f"  => LỖI THỰC THI: {str(e)}\n")



--- PHẦN 5: KIỂM TRA TÍNH HẠNG VÀ CƠ SỞ MA TRẬN BẰNG HÀM rank_and_basis(A) ---


[Test Case] Case 1: Ma trận đơn vị 3x3

  + Rank tìm được: 3 (Kỳ vọng: 3)

  => TRẠNG THÁI: [ ĐÚNG ]

  + Row Basis count: 3

  + Col Basis count: 3

  + Null Basis count: 0


[Test Case] Case 2: Ma trận suy biến

  + Rank tìm được: 1 (Kỳ vọng: 1)

  => TRẠNG THÁI: [ ĐÚNG ]

  + Row Basis count: 1

  + Col Basis count: 1

  + Null Basis count: 2


[Test Case] Case 3: Ma trận chữ nhật

  + Rank tìm được: 2 (Kỳ vọng: 2)

  => TRẠNG THÁI: [ ĐÚNG ]

  + Row Basis count: 2

  + Col Basis count: 2

  + Null Basis count: 2


[Test Case] Case 4: Ma trận toàn 0

  + Rank tìm được: 0 (Kỳ vọng: 0)

  => TRẠNG THÁI: [ ĐÚNG ]

  + Row Basis count: 0

  + Col Basis count: 0

  + Null Basis count: 3


[Test Case] Case 5: Ma trận 4x1

  + Rank tìm được: 1 (Kỳ vọng: 1)

  => TRẠNG THÁI: [ ĐÚNG ]

  + Row Basis count: 1

  + Col Basis count: 1

  + Null Basis count: 0



**ĐÃ HOÀN THÀNH XONG KIỂM THỬ**